Workspace
hallo-systems/lms-message pull request #7
Opened 2021-08-25 06:24 UTC by hallopm

2021-08-25 08:54 UTC, ymadd requested changes

2021-08-25 08:54 UTC, ymadd commented on script.js
>  var todayLessonType = "";
letへ変換

2021-08-25 08:54 UTC, ymadd commented on script.js
> +var typingType = "";
letへ変換

2021-08-25 08:54 UTC, ymadd commented on script.js
> +    let coachName = document.getElementById("coachname").value;
constへエラーが出るものへはletへ

2021-08-25 08:54 UTC, ymadd commented on script.js
> +        var pTitle = document.getElementById("title").value;
constへ

2021-08-25 08:54 UTC, ymadd commented on script.js
> +var message = "";
let へ

2021-08-25 09:33 UTC, ymadd requested changes

2021-08-25 09:33 UTC, ymadd commented on index.html
> +                            </div> -->
消していいよ

2021-08-25 09:33 UTC, ymadd commented on index.html
> +                            </div> -->
消していいよ

2021-08-25 09:33 UTC, ymadd commented on script.js
>      let month = date.getMonth()+1;
できるだけconstへ

2021-08-25 09:48 UTC, ymadd commented
あとversionを2.0.0へ変更して

2021-08-31 06:15 UTC, hallopm commented on script.js
> +});
変えました～！
最近は記号無しの傾向です？

2021-08-31 07:35 UTC, ymadd commented on script.js
> +});
最近というか基本的に記号は使わん方がええな、文字列内変数に使う可能性もあるし

2021-08-31 07:38 UTC, merged